// Generated by tool/export_netjeru.cjs. Content hashes match immutable asset URLs.
const netjeruArtAssets = <String, String>{
  'hetheru': 'assets/the_kar/hetheru.png',
  'khepri': 'assets/the_kar/khepri.png',
  'djehuty': 'assets/the_kar/djehuty-c18140680dbfd146.png',
  'maat': 'assets/the_kar/maat.png',
  'ptah': 'assets/the_kar/ptah-3241ff3442cb4fd6.png',
  'sekhmet': 'assets/the_kar/sekhmet-f28ff8fb2ebbb838.png',
};
