#!/usr/bin/env python3
"""Render replaceable first-pass recordings offline on macOS; run from RC root.
FFMPEG must name an installed FFmpeg executable. No cloud speech credentials.
The generated receipt binds the catalog input, render recipe and actual bytes.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
FFMPEG = os.environ.get('FFMPEG', 'ffmpeg')

def run(*args):
    return subprocess.run(args, check=True, capture_output=True).stdout

def digest(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()

def main():
    os.chdir(ROOT)
    rows = json.loads(run('dart', 'run', 'tool/export_pronunciation_review.dart', '--json'))['records']
    assert len(rows) == 54 and all(r['textStatus'] == 'textApproved' for r in rows)
    trim = 'silenceremove=start_periods=1:start_duration=0:start_threshold=-55dB,areverse,silenceremove=start_periods=1:start_duration=0:start_threshold=-55dB,areverse'
    normalize = 'loudnorm=I=-18:TP=-2:LRA=7'
    settings = dict(voice='com.apple.voice.compact.en-US.Samantha', locale='en-US', rate='145wpm', pauseMilliseconds=300, outputFormat='mp3/44100/mono/128k', normalizationFilter=normalize, edgeTrimFilter=trim, rendererVersion='macos-say-first-pass-v1', ffmpegVersion=run(FFMPEG, '-version').decode().splitlines()[0])
    manifests = {}
    with tempfile.TemporaryDirectory(prefix='haw-pronunciation-') as temp:
        for row in rows:
            # Render segments separately so the only pause is the exact catalog
            # gap; trimming cannot remove a deliberate internal pause.
            segments = [row['readerRespelling']]
            if row['meaning']: segments.append(row['meaning'])
            wavs = []
            for i, text in enumerate(segments):
                aiff = str(Path(temp)/f'{i}.aiff'); wav = str(Path(temp)/f'{i}.wav')
                run('say', '-v', 'Samantha', '-r', '145', '-o', aiff, text)
                run(FFMPEG, '-y', '-v', 'error', '-i', aiff, '-af', trim, '-ar', '44100', '-ac', '1', wav)
                wavs.append(wav)
            out = ROOT/row['audioAsset']; out.parent.mkdir(parents=True, exist_ok=True)
            if len(wavs) == 2:
                run(FFMPEG, '-y', '-v', 'error', '-i', wavs[0], '-f', 'lavfi', '-t', str(row['pauseMilliseconds']/1000), '-i', 'anullsrc=r=44100:cl=mono', '-i', wavs[1], '-filter_complex', '[0:a][1:a][2:a]concat=n=3:v=0:a=1,'+normalize+'[a]', '-map', '[a]', '-ar', '44100', '-ac', '1', '-codec:a', 'libmp3lame', '-b:a', '128k', str(out))
            else:
                run(FFMPEG, '-y', '-v', 'error', '-i', wavs[0], '-af', normalize, '-ar', '44100', '-ac', '1', '-codec:a', 'libmp3lame', '-b:a', '128k', str(out))
            run(FFMPEG, '-v', 'error', '-i', str(out), '-f', 'null', '-')
            manifests[row['key']] = dict(inputHash=row['inputHash'], renderFingerprint=digest(dict(schema=1, textFingerprint=row['textFingerprint'], inputHash=row['inputHash'], providerIpa=row['providerIpa'] or row['ipa'], settings=settings)), outputSha256=hashlib.sha256(out.read_bytes()).hexdigest())
            print(row['key'], out.stat().st_size, flush=True)
    quote = lambda s: "'"+s.replace('\\','\\\\').replace("'","\\'").replace('$','\\$')+"'"
    dart = "// Generated by tool/render_pronunciation.py. Replaceable first-pass audio.\npart of 'pronunciation_catalog.dart';\n\nconst _bundledRenderSettings = PronunciationRenderSettings(\n"
    for k,v in settings.items(): dart += f'  {k}: {v if isinstance(v,int) else quote(v)},\n'
    dart += ');\nconst _bundledPronunciationManifests = <String, PronunciationAudioManifest>{\n'
    for k,m in manifests.items():
        dart += f'  {quote(k)}: PronunciationAudioManifest(\n    settings: _bundledRenderSettings,\n'
        for field,value in m.items(): dart += f'    {field}: {quote(value)},\n'
        dart += '  ),\n'
    dart += '};\n'
    (ROOT/'lib/features/calendar/pronunciation/pronunciation_assets.g.dart').write_text(dart)
    (ROOT/'docs/pronunciation/audio-manifest.json').write_text(json.dumps(dict(status='replaceable-first-pass-not-listening-approved',settings=settings,records=manifests),indent=2,ensure_ascii=False)+'\n')

if __name__ == '__main__': main()
