// Generated by tool/render_pronunciation.py. Replaceable first-pass audio.
part of 'pronunciation_catalog.dart';

const _bundledRenderSettings = PronunciationRenderSettings(
  voice: 'com.apple.voice.compact.en-US.Samantha',
  locale: 'en-US',
  rate: '145wpm',
  pauseMilliseconds: 300,
  outputFormat: 'mp3/44100/mono/128k',
  normalizationFilter: 'loudnorm=I=-18:TP=-2:LRA=7',
  edgeTrimFilter:
      'silenceremove=start_periods=1:start_duration=0:start_threshold=-55dB,areverse,silenceremove=start_periods=1:start_duration=0:start_threshold=-55dB,areverse',
  rendererVersion: 'macos-say-first-pass-v1',
  ffmpegVersion:
      'ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers',
);
const _bundledPronunciationManifests = <String, PronunciationAudioManifest>{
  'month.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '57b3fabe1d2528f7aa849d1e16bc3431b1eb7f890c09187063f9aa5f0e4e0f84',
    renderFingerprint:
        'b3cfb9f189a7f274f1018904d28bb386f91c7fdacef5af56cffb29fb16bb0270',
    outputSha256:
        '4355b36ef8bd61a185c5fd709f0bcdb9c491b367d0f5fb7cb2d9a2a47c7094b4',
  ),
  'month.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'f6686fd054be4695f4f5c4250c7e67ad14fe182d9ff508441d053e0e052ecc2f',
    renderFingerprint:
        'fb8d0be4b7b67f28aff62eaf48aeed428e401b096b37a4bee8f9b784a40b88ff',
    outputSha256:
        '8c88ea182abd64794ac32d70911e7083db9ecfae62531b2cdd3676d70f9461ad',
  ),
  'month.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'e14b435654491f4b14989f1a780cdb5f6219dcb8208e151070e31d876d4caa60',
    renderFingerprint:
        'f57beb90aa7eeb562d6a8b6aff87475345b9774a8a13e956ff00e298f8300441',
    outputSha256:
        '4cc01324bb1412c1395e7c21d1df2bba20f90fe2b286092835b3e6560f1793bb',
  ),
  'month.04': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'bb0ab3c317a10ab73518060a8e451f001b69752440e5adeb553241a4346c82d4',
    renderFingerprint:
        '0713166caebf183219a5fc410d167200a6c2de3de5c7548e307664b7d5c315f1',
    outputSha256:
        'a5d4b8b6d758654d28f8dd719b71bcde7e100e0ac68c66369f81db59eca171e1',
  ),
  'month.05': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'ef67197247801737acc5635114c4acb5ec09f0ff3bc940377ad4dcab88c9eba6',
    renderFingerprint:
        '6d46bc3bb1fb6b1b760324c93c760a18b361df002f64b1df9e0a5e90053135b6',
    outputSha256:
        '1dad1207a9a4e23c0e7f726447414ffb86d2f0a1259282bfd1ac13df4f006a6a',
  ),
  'month.06': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '2edddb2f53e4dec13663fd93e142390beecca4ba588971d968b3b756e5a913bd',
    renderFingerprint:
        '1632a7edf7d9ef00e3045398f177e2314f4a9ff4878a6808d31bba9b86eecd27',
    outputSha256:
        'f67d5688c5400bb8acbebb4cf99f022565211f285445fda6c48dee29bd988d9e',
  ),
  'month.07': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '65b74ab373244efaba415233a9f9462159108557411752cc034d8090dd90d60e',
    renderFingerprint:
        'edf52dcc491ce2038ebd157a10f407c456c1ee63d5d2d0f801c07d3a66028aa7',
    outputSha256:
        '9c06a646e2d8f387818da98ed9a2021db413f02e7845d6097aa3e783c5e9c469',
  ),
  'month.08': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'baec678c7a9feb6d1b23c112149afda5db6acd962d4ae1bdf791d3ab18e75ca0',
    renderFingerprint:
        '05633374476eee567c1c27118678ab923b3cf41e0f4cd18e7361fdfe3cf9cd23',
    outputSha256:
        'e22fba4f1995b6748974264ae3bdc7bfc80aba84417f746172580fe648873fd0',
  ),
  'month.09': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'b291ce95d9cbc046e833dc8a14e7990bbb45ef318e290953448c2de9dcf76a96',
    renderFingerprint:
        'df596a3be4cfa7f365a38ed3109ae42fa52bd95b162b89586175127d5c517472',
    outputSha256:
        '9460a8273dda0dd55812748dc66abb887d330bfdcc8d4f1eb3ad5f6cedb930e1',
  ),
  'month.10': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '31e5b7f836868cbfe94ec3bbedb1ee0d60e28b8bb20194f7066f3142f86cdf6e',
    renderFingerprint:
        '7c9422ee159e2d9bae5c32c2ff0872826239b10d93c38ad93e789cc6fab9ed37',
    outputSha256:
        '9247e8b89d3600e8903332f69d6acc96bac1f7271915d5a687d1b5693c5e8e05',
  ),
  'month.11': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '6b908c3e2c397b513e9255ffc95b42a7232d2c169d121ad2dcf7e208db9fc5b4',
    renderFingerprint:
        '1fadea1c7750922e97769f4c6d8eb955e14591b92c9f2ed18d0e8c0dd1622534',
    outputSha256:
        'c1d0ab679fc56692e7f2c820695cde314d4d2f7b5c651ab00271984aa95ae96a',
  ),
  'month.12': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'ccd5f05d0704065007aa07fd8711ce6f3e4aa9b66d4cf7d1de31743d9e69edd0',
    renderFingerprint:
        '2ef23fe86e638215f8690dbca20e342d6dca118fdb8adc25a063e08ed2a3d20d',
    outputSha256:
        '515713cbc9e521804a76f3a5a9c40c12ed0d69023adf948972e28f7e11d3a880',
  ),
  'heriu-renpet': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'ca870e864534f4f4e55c833e8c0e83b86400bc27a7f605aa13b7cd4966069697',
    renderFingerprint:
        '6657e9fb7006c2e9741cba0f321d97a98ac89c27b43b78c817cf2463297d15f1',
    outputSha256:
        'c5a7bbb53f9a8feb687d5ee9e800a2a7b679d84c94f02a97126f5157414e9377',
  ),
  'decan.01.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '22e8ddbeae90c1bb0d65c8304c3bed81ae29d024da931b7c8e40d049c1c3a774',
    renderFingerprint:
        '8a34f16b21af8e893b053fff18a2d6eb10ba1b454e2b251fe73b117e7eb17063',
    outputSha256:
        'c251a385949aa5e79db02cbf8dda8f24c24c40ca537e70bbf929144313c4b397',
  ),
  'decan.01.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'ba4c69ddf52a321a88b600979e42cfba3db73932b4c7f09a3835d95086e7f23e',
    renderFingerprint:
        '07d1a6f74dc05eb9e978932c7c2129eb38a07f85f028d3e2869bafb3c4cb91dc',
    outputSha256:
        '620cd1d459f9eaa2818234b0bcd69da75b4aba3e532b62ad29e090178cfad3eb',
  ),
  'decan.01.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '071635fe9596b2b7eb5f174a438dd538889200288ebf42cfb6d3612974fa8edb',
    renderFingerprint:
        '2c15e35fe93bae5fe0a5f0f9a9d1eb3c3f178748376fc0870b77fff1fbbb43fd',
    outputSha256:
        '2dd800d93fcb295d81bc8dc1c8ec61065e344a542a588fc757fde25c6186cf38',
  ),
  'decan.02.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '73fa9bd63728a6480da01c0450f70fca489cf6918c08929c0cb6ef9d1acfa04b',
    renderFingerprint:
        '3a74484310a732fdfee343cefce14c04e3edee79795f1c77b30abfe64e1aca07',
    outputSha256:
        'c74857847a4ebf6796fdd475ad998758b834d995c2c73c4d9d6bfa556e3e1c08',
  ),
  'decan.02.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '21821d7707a9ff057deadfdb921f15c0206690b4470afe3039ba463704207e87',
    renderFingerprint:
        'c6df03a9420c6f8bb534f27e3658ff39609efe109abdea0babe6be29ee485633',
    outputSha256:
        '91d5f7745d88b60ea6c1b66bd70e730a055caa7fb994c6ad999f7ff6e03ba1c2',
  ),
  'decan.02.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'f323d598424a24042f4c2dc6b02acf024b1635e4448e6e27e90c4620cc3e4532',
    renderFingerprint:
        'd2b82b86aa93cf9db200d102240ec4e0ac30b5a4f223185fda3f9f4b4cfab61f',
    outputSha256:
        '6f422c2956344895938e0f5d0bf714068dc653f36644dc30db5e8986a507bb7d',
  ),
  'decan.03.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '273849daca7f1bce93a2c90aa257a7c0df7208e36994b7ce5050c4b0303417b6',
    renderFingerprint:
        'fed36facaffef5cde91e11f4239b58b39f0d20e0c864b1bc15065a9befa9facb',
    outputSha256:
        '82f577a90666b9e5966014c4f3b4519e4764cee1ebc56e9fb88d4382b9c1c191',
  ),
  'decan.03.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '7e1de16249624ade0d789d1c2f9d39997bede813b0bdd2054dc5f08715a72f4c',
    renderFingerprint:
        'fef5e733f1c73c39b7b16ea83952884e6597d15020d6a56c1cc8c1cf953c1f52',
    outputSha256:
        'fb7faab64c7bd25203cf7cfda9a984e53bebcb9e6e6aa5e9306247e0f2ac71d3',
  ),
  'decan.03.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'b367b4d7edeb624d70031d8e4d8a46e0fc1a577043ac626d33ca2b6f6c7ff882',
    renderFingerprint:
        '55d6aff1c66c434679cb7b80b4a0901d446aa91879a89075f995c5131275e88c',
    outputSha256:
        '626568a7784b0db080bd255ea331de798344551756798bf4e77fb3050a9d5e78',
  ),
  'decan.04.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '7ad338477545abaa15215e033e1046cd799bbb2079b317bd90431272d9fe9c28',
    renderFingerprint:
        'fb362870aba554baabd43a6d50378a83326ee414deb6df3b748b30f5ffbecc7c',
    outputSha256:
        'b9e908988c3b793d1e9f785e56a873e6de626bb05d443f40fbb6674b13d13374',
  ),
  'decan.04.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'fd9cf36b9b1e40d4e5575ff6fc401c6806dbb2f5bc3b275949b7e755dc60049b',
    renderFingerprint:
        '9a79f9307d21a321f3650331ecec4550489057f1f233325ea35a3c788b823277',
    outputSha256:
        'fa4b09e3a4edfb64e51fb2be36a921e597ecc9f326c3816f127cc4ee65f505d5',
  ),
  'decan.04.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'aee3a98be14732f8f9bc142bc38a9298b63b61e7e314b99d2b5056b2845b059f',
    renderFingerprint:
        '52c33f6ebb07f2080cfe1a164b72cce70cbc536e499e07879bfcb252142b17c6',
    outputSha256:
        '573f34b41b2b1c3054167fd6d729a6619d3f4675d2cd7e29de8aaaa107e4addd',
  ),
  'decan.05.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '235bb3818c3407dd04353a0895e7dc253f2b1b81ec1f401c456d5511c62603ba',
    renderFingerprint:
        '6c325a8614efe78e77589672e516f8e3452c3c68c19f870e654cd47d82cdc988',
    outputSha256:
        'fa7834c7fdc15f0a2eb8db541a28cadbd718247e13989b25026c4123409c608e',
  ),
  'decan.05.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '4eaed44ec56d7200d8374f459ade92d7517fe7848c05ecff7582cf3c17e2e62c',
    renderFingerprint:
        '47d7b36cce37d626bd5feef20f1ae93d833436757c567dcb95db07696fd8f29d',
    outputSha256:
        '28e315c88aa81651e6f20b564ac54cf6419487ea7375d701ac9f7e2d64f682d3',
  ),
  'decan.05.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'a3425e3adec37573c6b254e6fd90bbffb6175f14ee5fcc7c5662e851438d66c4',
    renderFingerprint:
        '577e599bfd0f7727476ffd87adb1a2e38b2b53d21e7ce2f65b81d0ab321e7025',
    outputSha256:
        '10118804936c2cdafaf620936ad21d279b9de10da22ec1e67a60ebb453588f70',
  ),
  'decan.06.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '51aa26b2075ce9826ca94e9981a9d6a87e85c55439b4a505f91fa272cdaf66c7',
    renderFingerprint:
        'a6da09f5d1f6d7a231e2481b831a509ec2db9b50af4c8fd74be97eb0c34cdab7',
    outputSha256:
        'ba72d6d37423cabe15126e7386d04d65d6b08df8dc1faab4fa83c719156b30ae',
  ),
  'decan.06.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'c6f839beb4a40a9750fca5eb915174295ae89fe2a6f3edf9a259e3e1b71de817',
    renderFingerprint:
        '7198fdc31003968ef10fb6f641729c961d552fb5d3def7f614e0c5bf124bbdc2',
    outputSha256:
        '37b30de4bdc99865686e63a50e9b5db8d195a102aedb8b166677a6fcc6b9fd5d',
  ),
  'decan.06.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '92a4253fc59cc2b3d82183c8c832f4b6a26e6c34ba35d57b749430163b8b1b50',
    renderFingerprint:
        '50cb86e5e4b08dc1ec90772a51064b44eed3dc33d5f1642a6919dae5e88a4715',
    outputSha256:
        '43f4130a893498aeea8ce734254f00e6f5d2dda7e4bc226709a32076bfe69357',
  ),
  'decan.07.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '095520c7ce16e300c780a1c9e1b00edf3436f9fe5f06c117c154aaa74e7d0458',
    renderFingerprint:
        '93d3bdd3150ef63e530b04e92d4c2536cf7d2485c6909973d760573e44baf9c5',
    outputSha256:
        '26a5b241408ffbd8b6742617ecd28106797fddbb2f5ad143fd543a7d6f902abc',
  ),
  'decan.07.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '3e3761a4a186bf5d65a59966c6b4dc7716841d393c4cf26ff2805aedcc18674c',
    renderFingerprint:
        '66a622e221061f5888cfc548a3fc13e67f28b6bf2f38be14ab59f7bf85dfc213',
    outputSha256:
        '332333c38b568de78f483355b221126e5d1728d8e071844fb6b71f989e6eec4c',
  ),
  'decan.07.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'c17216b25a5d7ce198179b34a26b224cdbcf9a049f422baa40e6a7a99832d0e3',
    renderFingerprint:
        '360801fef81a1c0763861abe30a162051ed60ca315aa430155ab0fa9b5eb6b1f',
    outputSha256:
        '58ba7c3fd96ab7869ef13638282f74385e4d752c8a3a7822e1b796920a7acb9b',
  ),
  'decan.08.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'e9071ede907f0cd4a259b7e3974e8a73d408c17c731f5c41fece1c5fc1411d0b',
    renderFingerprint:
        '8292c632cd9fb9407540401bcade5572cdfecfad2ce4a78b2ee86e05eb0f261e',
    outputSha256:
        '0c89c6916f305312856043a1501e3fdb29b6aee09c6444316cd8d31fb81dcd29',
  ),
  'decan.08.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '64271a6a13bbe01b5d68576d2d8f1e76c00a8e107f234cb91727cd898e88d0e0',
    renderFingerprint:
        'c35833f9d136969d0268b63cc1dc806896c52544f470c532fc2f558ed374f872',
    outputSha256:
        '8e09f5ae747d8f50b9c969673866220a0c25ddc0716d839206b934b88ceafea0',
  ),
  'decan.08.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'e2ad47148624cfbb5b479d89df29aa1babb4d748e5dbdce6611cfcb7288a4abe',
    renderFingerprint:
        'a6ee2e8ff941bbdfd149501b3b69edfc428fde479d5d039106c9a99b484a3beb',
    outputSha256:
        'a976adf57f5f4c0fb725b5117fc97f29995fe42545c52ca8f48a8ca356e46184',
  ),
  'decan.09.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '606ddb7adb5aff93b2320c9859169a7bee76d1df33edafe6e832c93e512f3b2d',
    renderFingerprint:
        '36a3e6c875563c88e4d0b33ed46de5ad3ab1cfc4b80e902343cfab0798c741ff',
    outputSha256:
        'f4ce2f6b8aa9cce1f5214c7a77d4434e042dc393a4c9ac98e3deda099d7bdc75',
  ),
  'decan.09.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '7f8693f5bd29e363178bc51d5fae49d414d5c756821c9f8cc47ebea08aa625e1',
    renderFingerprint:
        '715dc1c405585d38464286a57527aea5eaeb607498499cef89f4b11af7d15fd8',
    outputSha256:
        '99d9fd8f766274f0b062cadb05e0f534b0652cc8a4a222a6d2b5a646c99a212b',
  ),
  'decan.09.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '03097fcafeaa2e313d9cc57ee125d415b5599f9fcaed181d72e51139c7d8774c',
    renderFingerprint:
        '8602b2f0c9ccb03dc5d652c6ca6562ef8da0e8c61a09b54d724c9e5d8cff74de',
    outputSha256:
        '5a6365653366e976b94e80810375bab18fc0d570206d6a3c553d1b6a2f739152',
  ),
  'decan.10.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'b54fd67975d583bf1ab48027be84cdc11761b159d3b6749bc8bc322f05995e93',
    renderFingerprint:
        '461ece5304ce48f9e6d2177c4227d2214f331c6fe890f1b50e9a89221aa9d95c',
    outputSha256:
        '6d8a2cd4be93beda35d0e2da3340dbdf410672df3be709287955db4792468274',
  ),
  'decan.10.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '12187607df04d9a7da30241d63280ea80767472b94e249e7aa8c8fd2b12a92c7',
    renderFingerprint:
        'dd2e9faf9188079fe75cfabbdd42c53b07f12766636ee1941d3e7cf85919767a',
    outputSha256:
        '82cda8cd2ce061d38136346c398c03c1013a37e7523218840dc3f3467bcc3373',
  ),
  'decan.10.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'aa9598f42322f11f9bc0fd3188101f219aeabab0f63f07570962d4e222407cfd',
    renderFingerprint:
        '2e28ec59c18b6aa280a0d1c4fe553467c29d95240a55c54446d12918ac7c351a',
    outputSha256:
        'a778770924c40f154e5036c4e16676e275337260c0564d555e400215342548b2',
  ),
  'decan.11.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'f323d598424a24042f4c2dc6b02acf024b1635e4448e6e27e90c4620cc3e4532',
    renderFingerprint:
        'dc14109e21e8278d44264654f4ebf58e316ef817adb82fccd4aa752b520f7bd9',
    outputSha256:
        '6f422c2956344895938e0f5d0bf714068dc653f36644dc30db5e8986a507bb7d',
  ),
  'decan.11.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '17ad7edc03afb8434e8cb51b69c3ee99262ef76a7dc9761f4ba0be856e80e133',
    renderFingerprint:
        '5a8bf848aa3fb90d929420b7eac12ee5f4b2ceb58f5dd439bd759fb461c1ff86',
    outputSha256:
        '4690cd983ef5f4cbba2600bd8eb44b638aed35b10cc21d712202f9eed34b0b16',
  ),
  'decan.11.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'b9e8b36e7e946aff2df90029e81ce5981789fc7876f75f8c630cd630cf200134',
    renderFingerprint:
        '397f171a512741f4fe3c3811d1ba8c0a9216141aa0809da9423ea410d39a2151',
    outputSha256:
        '6e3aec7c1c3ec155cda2e849d310df61a84a4c3ed2fdf711c811f17766df0962',
  ),
  'decan.12.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '70968b770fb94b66f66c543a0d98ac8df8a6f09efdb41d1de107d4a7e6e6f82f',
    renderFingerprint:
        'df11ea4a6b70cb1f6adc5fdcb0df3bbc59b92576d5956a181dfde52588ed52c4',
    outputSha256:
        'fb46a514c148fdb2fc59bd22c39abfa06f0e452123475ec56b323eabcb1d99c5',
  ),
  'decan.12.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '49bd14bfd995c0e9370c48c760d68d8de87b1534b955951dd80cf38ff444bf50',
    renderFingerprint:
        'ecd5776351fb07e7e2bfbe59633a7edf8d71ebcf16fe678a91ded71f1571c32d',
    outputSha256:
        'fd35f84e715a91ec0794fa94bb985919700b72c65d964112ece8e697d0a9a342',
  ),
  'decan.12.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'd3eda3b03173d6f947f201fd9493151a9fb6f5aa30ef369dc0b6a21def59a426',
    renderFingerprint:
        'a6200fc44c799f15c44df3db5fc2fefefb345139d710a2b87b43804295865794',
    outputSha256:
        '9448e50aee4c6f16d9bf7336a90c94901c7dca4adfb6378fa10ab22333ec72e6',
  ),
  'epagomenal.01': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'a605752288dfb65a345ea733cd7308532cebfc82fdbd8086269f2c1997b1e56a',
    renderFingerprint:
        '3e83732e4dfee8ed1b8e2c56736f0170b06382179baf3b4357eaec5e0a39f3a6',
    outputSha256:
        '09b76e990553ec5a9fda6c72a4fb6bd628d92225e197e9bad667f5e79f5e2a6d',
  ),
  'epagomenal.02': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'da35aa25898a16ddb336d112e0447a399c2602d429d5f0ff9c7d4b3a52c4e931',
    renderFingerprint:
        '6202d8c5282788585ea205c41f6d7aba74a57fec7ea9df1177cb2743b1845734',
    outputSha256:
        'd6d5679b3f02fbfee8a5d149ac7f8adf7ebbee7c2e74f737d835acdcdc16c24f',
  ),
  'epagomenal.03': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'bafe288eef4b388d1de922837c7b841ba58a12ccdfcd43a4780286ef46d4b37e',
    renderFingerprint:
        'beffb6ceaba41d33bd7bdb3dbddbbefaa969dabe18ceda9b5a677e1af7e9bb48',
    outputSha256:
        '1098f7042a15ab2cc0b43e915c5ade083bb21de7216b3163b6f1bf1260b054c4',
  ),
  'epagomenal.04': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        'e8b130dbc23594224761b03948abe7db2952015d97d863f0ea6249735f12425b',
    renderFingerprint:
        '8f01eac04272bf4e6ff69eefc9054194820e8a3d0e5a6351b41d9f1563c865d7',
    outputSha256:
        'be11f6949295c32c341797cb8d19641850ac83213a7a28b05d1f44dea9204ddd',
  ),
  'epagomenal.05': PronunciationAudioManifest(
    settings: _bundledRenderSettings,
    inputHash:
        '20f64fdca84a2e2bfbf7ca3cc889f2e20a90fbda6fd053d786d641c3fac6b3d6',
    renderFingerprint:
        '8b8416ab6d20dd781e6c95225a0521a9a512a7b1ed0d4dec6bdb7495c4fdf2a7',
    outputSha256:
        '416f21a056f347a9348408f4a1d3489eef14d69aa16a03db51ea7a983e929c02',
  ),
};
