part of 'kemetic_day_info.dart';

final Map<String, KemeticDayInfo> _dayInfoMap = <String, KemeticDayInfo>{}
  ..addAll(_dayInfoMapBase1)
  ..addAll(_dayInfoMapBase2)
  ..addAll(_dayInfoMapBase3)
  ..addAll(_dayInfoMapBase4)
  ..addAll(_buildShefBedetIEntries())
  ..addAll(_buildShefBedetIIEntries())
  ..addAll(_buildShefBedetIIIEntries())
  ..addAll(_buildMesutRaIEntries())
  ..addAll(_buildMesutRaIIEntries())
  ..addAll(_buildMesutRaIIIEntries())
  ..addAll(_buildHeriuRenpetEntries())
  ..addAll(_buildRekhWerIEntries())
  ..addAll(_buildRekhWerIIEntries())
  ..addAll(_buildRekhWerIIIEntries())
  ..addAll(_buildRekhNedjesIEntries())
  ..addAll(_buildRekhNedjesIIEntries())
  ..addAll(_buildRekhNedjesIIIEntries())
  ..addAll(_buildRenwetIEntries())
  ..addAll(_buildRenwetIIEntries())
  ..addAll(_buildRenwetIIIEntries())
  ..addAll(_buildHnswIEntries())
  ..addAll(_buildHnswIIEntries())
  ..addAll(_buildHnswIIIEntries())
  ..addAll(_buildHentiHetIEntries())
  ..addAll(_buildHentiHetIIEntries())
  ..addAll(_buildHentiHetIIIEntries())
  ..addAll(_buildPaIpiIEntries())
  ..addAll(_buildPaIpiIIEntries())
  ..addAll(_buildPaIpiIIIEntries())
  ..addAll(_compressedDayInfoMap);
