import '../domain/track_sky_course.dart';
import 'course_measurement_service.dart';
import 'follow_sky_course_ownership.dart';
import 'track_sky_course_source_identity.dart';

/// One persisted calendar block, reduced to the fields Follow the Sky is
/// allowed to reason about.
///
/// Deliberately excludes the title: V2 never asks what a block *is* by reading
/// text. Attribution comes from the Protect Time ownership stamp or from the
/// flow the Course is Connect-linked to.
class FollowSkyCalendarBlock {
  const FollowSkyCalendarBlock({
    required this.start,
    required this.end,
    this.flowId,
    this.actionId,
    this.behaviorPayload,
  });

  final DateTime start;

  /// Raw persisted end. May be missing or malformed; see [normalizedEnd].
  final DateTime? end;

  /// Owning flow, when the block was generated by one. Protect Time blocks are
  /// ordinary single calendar events and carry no flow.
  final int? flowId;

  final String? actionId;
  final Map<String, dynamic>? behaviorPayload;

  /// A zero-length or inverted block still represents time the user gave.
  static const Duration minimumSpan = Duration(minutes: 30);

  DateTime get normalizedEnd {
    final raw = end;
    if (raw == null || !raw.isAfter(start)) return start.add(minimumSpan);
    return raw;
  }

  int get minutes {
    final span = normalizedEnd.difference(start).inMinutes.abs();
    return span <= 0 ? minimumSpan.inMinutes : span;
  }

  /// True when Follow the Sky created this block via Protect Time.
  bool get isProtectTime =>
      FollowSkyCourseOwnership.isProtectTime(behaviorPayload);

  /// Course this block was protected for, when it carries the stamp.
  String? get protectedCourseId =>
      FollowSkyCourseOwnership.courseIdOf(behaviorPayload);

  /// A Protect Time block is a plain calendar event, never a permanent Flow.
  bool get isSingleCalendarBlock => flowId == null || flowId! <= 0;
}

/// Decides which persisted calendar blocks a Course is allowed to measure.
///
/// Cut 1.2 authority: a Course becomes measurable on either ground, and Connect
/// is not a precondition.
///
/// - **Protect Time** — the block carries this Course's ownership stamp.
/// - **Connect** — the block belongs to the flow the Course is linked to.
///
/// Each block yields at most one interval, so a block that somehow satisfies
/// both grounds is never counted twice.
class FollowSkyCourseAttribution {
  const FollowSkyCourseAttribution();

  bool attributes({
    required TrackSkyCourse course,
    required FollowSkyCalendarBlock block,
  }) {
    if (block.protectedCourseId == course.courseId) return true;
    final linkedFlowId = TrackSkyCourseSourceIdentity.tryParseFlowId(
      course.sourceId,
    );
    if (linkedFlowId == null) return false;
    return block.flowId == linkedFlowId;
  }

  /// Intervals the Course may measure. Empty when there is no Course — an
  /// absent Course never inherits someone else's protected time.
  List<CourseMeasurementInterval> intervalsFor({
    required TrackSkyCourse? course,
    required Iterable<FollowSkyCalendarBlock> blocks,
  }) {
    if (course == null) return const <CourseMeasurementInterval>[];
    final out = <CourseMeasurementInterval>[];
    for (final block in blocks) {
      if (!attributes(course: course, block: block)) continue;
      out.add(
        CourseMeasurementInterval(
          start: block.start,
          end: block.normalizedEnd,
          minutes: block.minutes,
        ),
      );
    }
    return out;
  }
}
