import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mobile/features/calendar/follow_the_sky/follow_the_sky.dart';

/// Cut 2 — what happens to a Connect-linked Course when the source it points at
/// is renamed or deleted. Gate 16 is proved at the resolver elsewhere; here it
/// is proved through the measurement rule and the surface the user sees.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late SkyCatalog catalog;

  setUpAll(() {
    catalog = SkyCatalogRepository.parseJsonString(
      File('assets/follow_the_sky/sky_catalog_v2.json').readAsStringSync(),
    );
  });

  final codec = TrackSkyCourseMetadataCodec();
  const attribution = FollowSkyCourseAttribution();
  const functions = CourseFunctionService();
  final now = DateTime.utc(2026, 8, 28, 12);

  final enrollment = TrackSkyEnrollmentService(
    materializer: TrackSkyMaterializer(
      toLocal: (utc, _) => utc,
      toUtc: (local, _) => local,
    ),
    visibilityService: const SkyVisibilityService(),
  );

  /// The Course the user typed, before Connect gave it a calendar source.
  TrackSkyCourse freeText() => TrackSkyCourse(
        courseId: 'course-finish-my-book',
        label: 'Finish my book',
        sourceType: TrackSkyCourseSourceType.freeText,
        createdAt: DateTime.utc(2026, 8, 1),
      );

  CourseActivitySignal signal({
    required String label,
    required int flowId,
    int occurrences = 4,
  }) {
    return CourseActivitySignal(
      label: label,
      sourceType: TrackSkyCourseSourceType.flow,
      sourceId: TrackSkyCourseSourceIdentity.forFlow(flowId),
      occurrenceCount: occurrences,
      recentMinutes: 180,
      previousMinutes: 240,
    );
  }

  /// Blocks generated by a flow, as the calendar persists them.
  List<FollowSkyCalendarBlock> flowBlocks(int flowId) => [
        FollowSkyCalendarBlock(
          start: DateTime.utc(2026, 8, 18, 10),
          end: DateTime.utc(2026, 8, 18, 12),
          flowId: flowId,
        ),
        FollowSkyCalendarBlock(
          start: DateTime.utc(2026, 8, 25, 10),
          end: DateTime.utc(2026, 8, 25, 11, 30),
          flowId: flowId,
        ),
        FollowSkyCalendarBlock(
          start: DateTime.utc(2026, 8, 27, 10),
          end: DateTime.utc(2026, 8, 27, 11),
          flowId: flowId,
        ),
      ];

  TrackSkyCourse linkedToFlow11() {
    return enrollment.linkCourseToActivity(
      course: freeText(),
      activity: const CourseCandidateEngine()
          .eligibleForConnect([signal(label: 'Writing', flowId: 11)])
          .single,
    );
  }

  test('Connect makes the linked flow\'s own blocks measurable', () {
    final linked = linkedToFlow11();
    expect(linked.sourceId, 'flow:11');
    expect(linked.label, 'Finish my book');

    final intervals = attribution.intervalsFor(
      course: linked,
      blocks: flowBlocks(11),
    );
    expect(intervals, hasLength(3));

    final measure = functions.evidenceFor(
      function: SkyEventFunction.measure,
      course: linked,
      now: now,
      intervals: intervals,
    );
    expect(measure.available, isTrue);

    // A linked Course is the only kind with a carry-forward object.
    final reconsider = functions.evidenceFor(
      function: SkyEventFunction.reconsider,
      course: linked,
      now: now,
      intervals: intervals,
    );
    expect(reconsider.available, isTrue);
  });

  test('renaming the source flow keeps the link and the measurement', () {
    final linked = linkedToFlow11();
    final persisted = codec.decode(codec.encode(linked))!;

    final afterRename = enrollment.rehydrateCourse(
      course: persisted,
      flowsByServerId: {
        11: const HydratedFlowRef(serverId: 11, name: 'Writing — evenings'),
      },
    );

    expect(afterRename.isLinked, isTrue);
    expect(afterRename.sourceId, 'flow:11');
    // The Course keeps the name the user chose, not the flow's new name.
    expect(afterRename.label, 'Finish my book');
    expect(
      attribution.intervalsFor(course: afterRename, blocks: flowBlocks(11)),
      hasLength(3),
    );
  });

  test('deleting the source stops measurement and never adopts a namesake', () {
    final linked = linkedToFlow11();
    final persisted = codec.decode(codec.encode(linked))!;

    // Flow 11 is gone; flow 999 happens to reuse the label.
    final afterDelete = enrollment.rehydrateCourse(
      course: persisted,
      flowsByServerId: {
        999: const HydratedFlowRef(serverId: 999, name: 'Writing'),
      },
    );

    expect(afterDelete.isLinked, isFalse);
    expect(afterDelete.sourceType, TrackSkyCourseSourceType.freeText);
    expect(afterDelete.label, 'Finish my book');

    expect(
      attribution.intervalsFor(course: afterDelete, blocks: flowBlocks(999)),
      isEmpty,
    );
    expect(
      attribution.intervalsFor(course: afterDelete, blocks: flowBlocks(11)),
      isEmpty,
    );

    // Protect Time is still a route back to measurement after the unlink.
    final protectedBlock = FollowSkyCalendarBlock(
      start: DateTime.utc(2026, 8, 26, 9),
      end: DateTime.utc(2026, 8, 26, 10),
      behaviorPayload: FollowSkyCourseOwnership.behaviorPayload(
        courseId: afterDelete.courseId,
      ),
    );
    expect(
      attribution.intervalsFor(
        course: afterDelete,
        blocks: [protectedBlock, ...flowBlocks(999)],
      ),
      hasLength(1),
    );
  });

  testWidgets('the detail surface follows a renamed source', (tester) async {
    final linked = linkedToFlow11();

    await tester.pumpWidget(
      MaterialApp(
        home: FollowSkyDetailPage(
          isJoined: true,
          initialCatalog: catalog,
          existingFlowNotes: codec.encode(linked),
          candidates: [signal(label: 'Writing — evenings', flowId: 11)],
          now: now,
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('Finish my book'), findsOneWidget);
    expect(find.text('Connected to Writing — evenings'), findsOneWidget);
  });

  testWidgets('after a deleted source the surface re-offers Connect', (
    tester,
  ) async {
    final linked = linkedToFlow11();
    final unlinked = enrollment.rehydrateCourse(
      course: codec.decode(codec.encode(linked))!,
      flowsByServerId: {
        999: const HydratedFlowRef(serverId: 999, name: 'Writing'),
      },
    );

    await tester.pumpWidget(
      MaterialApp(
        home: FollowSkyDetailPage(
          isJoined: true,
          initialCatalog: catalog,
          existingFlowNotes: codec.encode(unlinked),
          candidates: [signal(label: 'Writing', flowId: 999)],
          now: now,
        ),
      ),
    );
    await tester.pumpAndSettle();

    // Course survives; the claim of a connected source does not.
    expect(find.text('Finish my book'), findsOneWidget);
    expect(find.textContaining('Connected to'), findsNothing);
    expect(find.text('No calendar activity connected yet'), findsOneWidget);
    expect(find.text('Connect activity'), findsOneWidget);
  });

  test('Connect offers sources the suggestion chips would not', () {
    const engine = CourseCandidateEngine();
    final thin = [signal(label: 'Writing', flowId: 11, occurrences: 1)];

    expect(engine.suggest(thin), isEmpty);
    expect(
      engine.eligibleForConnect(thin).map((c) => c.label),
      ['Writing'],
    );
  });
}
